In [2]:
import numpy as np #alias

<H1>Array Reshaping -> Reshape, Ravel, Flatten</H1>

In [64]:
#Reshape
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [65]:
reshape2 = reshaped.reshape(3,2)
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
#ravel -> convert 1D array
ravel = reshaped.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [68]:
#Flateten -> to 1D array
# -> returns a copy of the array
# It don't change the original array it gives its copy 

flat = reshape2.flatten()
flat

array([1, 2, 3, 4, 5, 6])

In [69]:
flat[0] = 100

In [70]:
flat

array([100,   2,   3,   4,   5,   6])

In [71]:
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])