In [1]:
import numpy as np

In [8]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
result = np.where(arr1<5, "Low", "High")
result

array(['Low', 'Low', 'Low', 'Low', 'High', 'High', 'High', 'High', 'High'],
      dtype='<U4')

In [5]:
# argwhere : row-column position for 2d arrays 

In [10]:
arr2 = np.array([10,20,25,35,47,89])

In [13]:
print(np.argwhere(arr2>25))

[[3]
 [4]
 [5]]


In [25]:
mask = np.logical_and(arr2>20, arr2<35)
print(mask)

[False False  True False False False]


In [21]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [23]:
print(np.argwhere(matrix > 5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]
