In [1]:
import numpy as np

In [2]:
a = (1,2,3,4,5)
# indexes 0,2,4
a[::2]

(1, 3, 5)

In [6]:
a[-1:-4:-1]

(5, 4, 3)

In [7]:
arr = np.array([10,20,30,40,50])
#index 0,2,4
arr[::2]

array([10, 30, 50])

In [10]:
# Negative indexing
print(arr[-1])

50


In [13]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]


In [18]:
print(matrix[1: , 1:])

[[5 6]
 [8 9]]


Index array -> Advanced Indexing

In [22]:
#np.take -> builtin function to perform indexing and slicing
arr = np.array([10,20,30,40,50])
ind = [0,2]
print(np.take(arr, ind))

[10 30]


In [25]:
# Iterating with nditer()
arr = np.array([[1,2],[3,4]])

for x in np.nditer(arr):
    print(x, end= " ") 


1 2 3 4 

In [26]:
# ndenumerate -> both index + value
for ind, x in np.ndenumerate(arr):
    print(ind,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
