In [7]:
import numpy as np

In [8]:
a = np.array([[1,2], [3,4], [5,6], [7,8]])
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [4]:
print(np.split(a, 2)) # To split arrays -> (name of matrix, num of split)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [5]:
print(np.split(a, 4)) 

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


#### array can split in equal parts if you try to split in unequal parts then it will give error

In [6]:
print(np.hsplit(a,2)) # Split horizontally

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


## Repeat vs tile

In [7]:
# Repeating 
arr = np.array([1,2,3])
print(np.repeat(arr, 2))

[1 1 2 2 3 3]


In [9]:
# Tile -> repeat my whole array
print(np.tile(arr, 2))

[1 2 3 1 2 3]


In [10]:
# Aggregate functions: 

arr = np.array([1,2,3,4])
print(np.sum(arr))

10


In [12]:
print(np.mean(arr))

2.5


In [13]:
print(np.median(arr))

2.5


In [14]:
print(np.std(arr))

1.118033988749895


In [16]:
print(np.var(arr)) # variants -> square of standard deviation (std)

1.25


In [17]:
print(np.max(arr))

4


In [18]:
print(np.min(arr))

1


In [23]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
print(np.sum(matrix, axis = 0)) # axis=0 is for row

[12 15 18]


In [27]:
print(np.sum(matrix, axis = 1)) # axis=1 is for column

[ 6 15 24]


In [9]:
# Cumulative Operations -> running total
arr = np.array([6,7,8])
arr

array([6, 7, 8])

In [10]:
print(np.cumsum(arr)) # 1st = 6, 2nd = 6+7 - 13 then at 3rd all three you got that point 

[ 6 13 21]


In [11]:
print(np.cumprod(arr))

[  6  42 336]
