In [2]:
import numpy as np

<h3>Views vs copies</h3>

<big> Views - </big> when we created a view of array the original array get affected <br>
<big> Copies - </big> when copy is created original array don't get affected

In [4]:
arr = np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [5]:
view[1] = 200
view

array([  2, 200])

In [13]:
arr # Here, original array get change

array([  1,   2, 200,   4,   5])

In [9]:
#copy
copy = arr[1:3].copy()
copy

array([  2, 200])

In [10]:
copy[1] = 100
copy

array([  2, 100])

In [12]:
arr # Here, original array get same no changes happen in it 

array([  1,   2, 200,   4,   5])

<h1>Transpose of matrix</h1>

In [15]:
arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [16]:
print(arr.transpose())

[[1 3]
 [2 4]]


In [17]:
# Swapaxes -> swap 2 specific axes in matrix
arr = np.array([[[1,2], [3,4]]])
arr.shape

(1, 2, 2)

In [19]:
swap = np.swapaxes(arr, 0, 1) # (name of array, 1st axes, 2nd axes)
swap.shape

(2, 1, 2)

# ___________________________________________

In [21]:
# Concatenation:
a = np.array([1,2])
b = np.array([3,4])

In [22]:
combine = np.concatenate((a,b))
combine

array([1, 2, 3, 4])

In [24]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [28]:
# Vertically stacked
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [29]:
# Horizontally stacked
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [33]:
print(np.stack((a,b), axis =  0)) # axis = 0 -> row wise

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
print(np.stack((a,b), axis =  1)) # axis = 1 -> column wise

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
