In [1]:
import numpy as np

Vectorization means performing operations on entire arrays at once, instead of using Python for loops.

In simple words:

❌ Loop → element by element ✅ Vectorization → whole array in one shot

NumPy is fast because it uses optimized C code internally, so vectorized operations are much faster than Python loops.

🧠 Why Vectorization is Important?

⚡ Much faster execution

🧼 Cleaner and shorter code

💾 Better memory usage

🔥 Required for ML / Data Science

In [2]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
result = []
for i in range(len(a)):
    result.append(a[i] + b[i])
print(result)

[np.int64(11), np.int64(22), np.int64(33), np.int64(44), np.int64(55)]


This is slow because:

<ul><li>Python loop runs every iteration</li>
<li>Each operation happens separately</li></ul>

In [3]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

result = a + b
print(result)


[11 22 33 44 55]


NumPy performs addition at low-level (C implementation) → much faster.

In [4]:
# broadcasting and Vectorization
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10, 20, 30])

print(A + B)

[[11 22 33]
 [14 25 36]]


In [5]:
# np.vectorize -> convert a regular function to be applied on an array

In [6]:
def square(x):
    return x * x


vfun = np.vectorize(square)

In [7]:
arr = np.array([2, 4, 5, 6, 7, 9])
arr

array([2, 4, 5, 6, 7, 9])

In [8]:
print(vfun(arr))

[ 4 16 25 36 49 81]
